/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Flavour = { 'aqi' : null } |
  { 'premium' : null } |
  { 'deluxe' : null } |
  { 'standard' : null };
export type Model = { 'N13' : null } |
  { 'N125' : null } |
  { 'N135' : null } |
  { 'others' : null };
export interface ReportEntry {
  'model' : Model,
  'validGpsFixPkts' : bigint,
  'weekYear' : string,
  'unitId' : string,
  'normalPktCount' : bigint,
  'totalPkts' : bigint,
  'storedPkts' : bigint,
  'storedPktCount' : bigint,
  'location' : string,
  'flavour' : Flavour,
}
export interface _SERVICE {
  'addDisplayColumn' : ActorMethod<[string], undefined>,
  'clearAllData' : ActorMethod<[], undefined>,
  'getAllReports' : ActorMethod<[], Array<ReportEntry>>,
  'getDisplayColumns' : ActorMethod<[], Array<string>>,
  'getReport' : ActorMethod<[string, string], [] | [ReportEntry]>,
  'getReportsByModel' : ActorMethod<[Model], Array<ReportEntry>>,
  'getUnitCount' : ActorMethod<[], bigint>,
  'removeDisplayColumn' : ActorMethod<[string], undefined>,
  'upsertBatchReport' : ActorMethod<
    [
      Array<
        [
          Model,
          Flavour,
          string,
          string,
          bigint,
          bigint,
          bigint,
          bigint,
          bigint,
          string,
        ]
      >,
    ],
    undefined
  >,
  'upsertReport' : ActorMethod<
    [
      Model,
      Flavour,
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];