/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UnitModel = IDL.Variant({
  'N13' : IDL.Null,
  'N125' : IDL.Null,
  'N135' : IDL.Null,
});
export const ReportEntry = IDL.Record({
  'unitModel' : UnitModel,
  'validGpsFixPkts' : IDL.Nat,
  'weekYear' : IDL.Text,
  'unitId' : IDL.Text,
  'normalPktCount' : IDL.Nat,
  'totalPkts' : IDL.Nat,
  'storedPkts' : IDL.Nat,
  'storedPktCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllReports' : IDL.Func([], [IDL.Vec(ReportEntry)], ['query']),
  'getReport' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(ReportEntry)],
      ['query'],
    ),
  'upsertReport' : IDL.Func(
      [
        UnitModel,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UnitModel = IDL.Variant({
    'N13' : IDL.Null,
    'N125' : IDL.Null,
    'N135' : IDL.Null,
  });
  const ReportEntry = IDL.Record({
    'unitModel' : UnitModel,
    'validGpsFixPkts' : IDL.Nat,
    'weekYear' : IDL.Text,
    'unitId' : IDL.Text,
    'normalPktCount' : IDL.Nat,
    'totalPkts' : IDL.Nat,
    'storedPkts' : IDL.Nat,
    'storedPktCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllReports' : IDL.Func([], [IDL.Vec(ReportEntry)], ['query']),
    'getReport' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(ReportEntry)],
        ['query'],
      ),
    'upsertReport' : IDL.Func(
        [
          UnitModel,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };