/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Model = IDL.Variant({
  'N13' : IDL.Null,
  'N125' : IDL.Null,
  'N135' : IDL.Null,
});
export const Flavour = IDL.Variant({
  'aqi' : IDL.Null,
  'premium' : IDL.Null,
  'deluxe' : IDL.Null,
  'standard' : IDL.Null,
});
export const ReportEntry = IDL.Record({
  'model' : Model,
  'validGpsFixPkts' : IDL.Nat,
  'weekYear' : IDL.Text,
  'unitId' : IDL.Text,
  'normalPktCount' : IDL.Nat,
  'totalPkts' : IDL.Nat,
  'storedPkts' : IDL.Nat,
  'storedPktCount' : IDL.Nat,
  'location' : IDL.Text,
  'flavour' : Flavour,
});

export const idlService = IDL.Service({
  'addDisplayColumn' : IDL.Func([IDL.Text], [], []),
  'getAllReports' : IDL.Func([], [IDL.Vec(ReportEntry)], ['query']),
  'getDisplayColumns' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getReport' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(ReportEntry)],
      ['query'],
    ),
  'getReportsByModel' : IDL.Func([Model], [IDL.Vec(ReportEntry)], ['query']),
  'getUnitCount' : IDL.Func([], [IDL.Nat], ['query']),
  'removeDisplayColumn' : IDL.Func([IDL.Text], [], []),
  'upsertBatchReport' : IDL.Func(
      [
        IDL.Vec(
          IDL.Tuple(
            Model,
            Flavour,
            IDL.Text,
            IDL.Text,
            IDL.Nat,
            IDL.Nat,
            IDL.Nat,
            IDL.Nat,
            IDL.Nat,
            IDL.Text,
          )
        ),
      ],
      [],
      [],
    ),
  'upsertReport' : IDL.Func(
      [
        Model,
        Flavour,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Model = IDL.Variant({
    'N13' : IDL.Null,
    'N125' : IDL.Null,
    'N135' : IDL.Null,
  });
  const Flavour = IDL.Variant({
    'aqi' : IDL.Null,
    'premium' : IDL.Null,
    'deluxe' : IDL.Null,
    'standard' : IDL.Null,
  });
  const ReportEntry = IDL.Record({
    'model' : Model,
    'validGpsFixPkts' : IDL.Nat,
    'weekYear' : IDL.Text,
    'unitId' : IDL.Text,
    'normalPktCount' : IDL.Nat,
    'totalPkts' : IDL.Nat,
    'storedPkts' : IDL.Nat,
    'storedPktCount' : IDL.Nat,
    'location' : IDL.Text,
    'flavour' : Flavour,
  });
  
  return IDL.Service({
    'addDisplayColumn' : IDL.Func([IDL.Text], [], []),
    'getAllReports' : IDL.Func([], [IDL.Vec(ReportEntry)], ['query']),
    'getDisplayColumns' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getReport' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(ReportEntry)],
        ['query'],
      ),
    'getReportsByModel' : IDL.Func([Model], [IDL.Vec(ReportEntry)], ['query']),
    'getUnitCount' : IDL.Func([], [IDL.Nat], ['query']),
    'removeDisplayColumn' : IDL.Func([IDL.Text], [], []),
    'upsertBatchReport' : IDL.Func(
        [
          IDL.Vec(
            IDL.Tuple(
              Model,
              Flavour,
              IDL.Text,
              IDL.Text,
              IDL.Nat,
              IDL.Nat,
              IDL.Nat,
              IDL.Nat,
              IDL.Nat,
              IDL.Text,
            )
          ),
        ],
        [],
        [],
      ),
    'upsertReport' : IDL.Func(
        [
          Model,
          Flavour,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };