/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ReportEntry {
    model: Model;
    validGpsFixPkts: bigint;
    weekYear: string;
    unitId: string;
    normalPktCount: bigint;
    totalPkts: bigint;
    storedPkts: bigint;
    storedPktCount: bigint;
    location: string;
    flavour: Flavour;
}
export enum Flavour {
    aqi = "aqi",
    premium = "premium",
    deluxe = "deluxe",
    standard = "standard"
}
export enum Model {
    N13 = "N13",
    N125 = "N125",
    N135 = "N135",
    others = "others"
}
export interface backendInterface {
    addDisplayColumn(columnName: string): Promise<void>;
    clearAllData(): Promise<void>;
    getAllReports(): Promise<Array<ReportEntry>>;
    getDisplayColumns(): Promise<Array<string>>;
    getReport(unitId: string, weekYear: string): Promise<ReportEntry | null>;
    getReportsByModel(model: Model): Promise<Array<ReportEntry>>;
    getUnitCount(): Promise<bigint>;
    removeDisplayColumn(columnName: string): Promise<void>;
    upsertBatchReport(entries: Array<[Model, Flavour, string, string, bigint, bigint, bigint, bigint, bigint, string]>): Promise<void>;
    upsertReport(model: Model, flavour: Flavour, unitId: string, weekYear: string, totalPkts: bigint, storedPkts: bigint, validGpsFixPkts: bigint, storedPktCount: bigint, normalPktCount: bigint, location: string): Promise<void>;
}
import type { Flavour as _Flavour, Model as _Model, ReportEntry as _ReportEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDisplayColumn(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDisplayColumn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDisplayColumn(arg0);
            return result;
        }
    }
    async clearAllData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllData();
            return result;
        }
    }
    async getAllReports(): Promise<Array<ReportEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReports();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReports();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDisplayColumns(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDisplayColumns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDisplayColumns();
            return result;
        }
    }
    async getReport(arg0: string, arg1: string): Promise<ReportEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(arg0, arg1);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(arg0, arg1);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportsByModel(arg0: Model): Promise<Array<ReportEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportsByModel(to_candid_Model_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportsByModel(to_candid_Model_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnitCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnitCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnitCount();
            return result;
        }
    }
    async removeDisplayColumn(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeDisplayColumn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeDisplayColumn(arg0);
            return result;
        }
    }
    async upsertBatchReport(arg0: Array<[Model, Flavour, string, string, bigint, bigint, bigint, bigint, bigint, string]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertBatchReport(to_candid_vec_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertBatchReport(to_candid_vec_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async upsertReport(arg0: Model, arg1: Flavour, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint, arg9: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertReport(to_candid_Model_n9(this._uploadFile, this._downloadFile, arg0), to_candid_Flavour_n13(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertReport(to_candid_Model_n9(this._uploadFile, this._downloadFile, arg0), to_candid_Flavour_n13(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
}
function from_candid_Flavour_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Flavour): Flavour {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Model_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Model): Model {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ReportEntry_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportEntry): ReportEntry {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReportEntry]): ReportEntry | null {
    return value.length === 0 ? null : from_candid_ReportEntry_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    model: _Model;
    validGpsFixPkts: bigint;
    weekYear: string;
    unitId: string;
    normalPktCount: bigint;
    totalPkts: bigint;
    storedPkts: bigint;
    storedPktCount: bigint;
    location: string;
    flavour: _Flavour;
}): {
    model: Model;
    validGpsFixPkts: bigint;
    weekYear: string;
    unitId: string;
    normalPktCount: bigint;
    totalPkts: bigint;
    storedPkts: bigint;
    storedPktCount: bigint;
    location: string;
    flavour: Flavour;
} {
    return {
        model: from_candid_Model_n4(_uploadFile, _downloadFile, value.model),
        validGpsFixPkts: value.validGpsFixPkts,
        weekYear: value.weekYear,
        unitId: value.unitId,
        normalPktCount: value.normalPktCount,
        totalPkts: value.totalPkts,
        storedPkts: value.storedPkts,
        storedPktCount: value.storedPktCount,
        location: value.location,
        flavour: from_candid_Flavour_n6(_uploadFile, _downloadFile, value.flavour)
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    N13: null;
} | {
    N125: null;
} | {
    N135: null;
}): Model {
    return "N13" in value ? Model.N13 : "N125" in value ? Model.N125 : "N135" in value ? Model.N135 : "others" in value ? Model.others : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aqi: null;
} | {
    premium: null;
} | {
    deluxe: null;
} | {
    standard: null;
}): Flavour {
    return "aqi" in value ? Flavour.aqi : "premium" in value ? Flavour.premium : "deluxe" in value ? Flavour.deluxe : "standard" in value ? Flavour.standard : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReportEntry>): Array<ReportEntry> {
    return value.map((x)=>from_candid_ReportEntry_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Flavour_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Flavour): _Flavour {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Model_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Model): _Model {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_tuple_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Model, Flavour, string, string, bigint, bigint, bigint, bigint, bigint, string]): [_Model, _Flavour, string, string, bigint, bigint, bigint, bigint, bigint, string] {
    return [
        to_candid_Model_n9(_uploadFile, _downloadFile, value[0]),
        to_candid_Flavour_n13(_uploadFile, _downloadFile, value[1]),
        value[2],
        value[3],
        value[4],
        value[5],
        value[6],
        value[7],
        value[8],
        value[9]
    ];
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Model): {
    N13: null;
} | {
    N125: null;
} | {
    N135: null;
} | {
    others: null;
} {
    return value == Model.N13 ? {
        N13: null
    } : value == Model.N125 ? {
        N125: null
    } : value == Model.N135 ? {
        N135: null
    } : value == Model.others ? {
        others: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Flavour): {
    aqi: null;
} | {
    premium: null;
} | {
    deluxe: null;
} | {
    standard: null;
} {
    return value == Flavour.aqi ? {
        aqi: null
    } : value == Flavour.premium ? {
        premium: null
    } : value == Flavour.deluxe ? {
        deluxe: null
    } : value == Flavour.standard ? {
        standard: null
    } : value;
}
function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Model, Flavour, string, string, bigint, bigint, bigint, bigint, bigint, string]>): Array<[_Model, _Flavour, string, string, bigint, bigint, bigint, bigint, bigint, string]> {
    return value.map((x)=>to_candid_tuple_n12(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
